version: '3'
services:
  app:
    container_name: CS-Server
    restart: always
    build: ./
    ports:
      - '5051:5000'
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
